# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sungsu Ahn
title: M.S./Ph.D. Student in Korea University
email: sungsu_ahn@korea.ac.kr
website: youkioh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  youkioh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/sungsu_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a M.S./Ph.D. student at Korea University focusing on computer architectures and system software. 
  My current research interests include **memory systems**, **operating systems**, and **CXL-based memory management** for datacenter.
  I am most skilled in: <mark>Linux memory management</mark>, <mark>C programming</mark>

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CXL Memory Management for Datacenter
        description: | # this will include new lines to allow paragraphs
          I am currently working on heterogeneous memory management for CXL-based memory systems in datacenter.
          My research focuses on the hotness-aware & timeliness-aware memory management with system software support.
          I am also interested in the performance evaluation of CXL-based memory systems.

  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IEEE TC
        # link_text: boringcompany.com
        sub_title: Top journal in computer architecture
        caption: 2026
        description: | # this will include new lines to allow paragraphs
          **Bauhaus: Restructuring Vector Database for LLM Retrieval on CXL-Based Tiered Memory**
 
          Kyungbin Kim, **Sungsu Ahn**, Wonjung Jeong, Jongmin Kim, Sangun Choi, Minseong Gil, Minseong Kim, Dongha Jeong, Yunjay Hong, Haekang Jung, and Yunho Oh  
          Accepted at IEEE Transactions on Computers.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University
        caption: 2024 - Present
        sub_title: M.S./Ph.D. in Electrical and Electronics Engineering with a specialization in Computer Engineering.
        description: | # this will include new lines to allow paragraphs
          I am currently studying at Korea University in ComSys Lab under the supervision of Prof. Yunho Oh.

      - layout: left
        title: Sungkyunkwan University
        caption: 2016 - 2024
        sub_title: B.S. in Electronic and Electrical Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science some of my other interests and hobbies are:
      - Novel & Poem
      - Game
      - Music [Spotify](https://open.spotify.com/user/31w37njobw7vygrvcjksk2gzb4lu?si=uULWP32GSiKpRRK_HHi6MQ)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
